version: '3'
services:
  laravel:
    build:
      args:
        - LARAVEL_UID=${LARAVEL_UID}
        - LARAVEL_USER=${LARAVEL_USER}
        - LARAVEL_HOME=${LARAVEL_HOME}
        - LARAVEL_DIR=${LARAVEL_DIR}
      context: docker/laravel
    container_name: php-laravel9-example-laravel
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - GIT_COMMITTER_NAME=${GIT_USER_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_USER_EMAIL}
      - GIT_AUTHOR_NAME=${GIT_USER_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_USER_EMAIL}
    ports:
      - "8000:8000"
    tty: true
    user: ${LARAVEL_UID}:www-data
    volumes:
      - ./laravel:/laravel
      - ./docker/laravel/.vscode-server:${LARAVEL_HOME}/.vscode-server
      - php-socket:/var/run/php
    working_dir: /laravel
  nginx:
    build:
      context: docker/nginx
    container_name: php-laravel9-example-nginx
    depends_on:
      - laravel
    ports:
      - "80:80"
    volumes:
      - ./laravel/public:/var/www/html
      - php-socket:/var/run/php
volumes:
  php-socket:
